name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set default rust channel to nightly
        run: rustup default nightly
        
      - name: Build Helios
        run: cd helios && cargo build --verbose
        
      - name: Build Ares
        run: cd ares && cargo build --verbose
